project:
  type: website
  output-dir: docs

website:
  title: "Pranjal Chatterjee"
  search: false
  navbar:
    pinned: true
    left:
      - href: index.qmd#background
        text: Background
      - href: index.qmd#experience
        text: Experience
      - href: blog.qmd
        text: Blogs

format:
  html:
    css: assets/theme.css
    include-after-body: assets/scrollspy.js
    highlight-style: github
    code-copy: true
    code-line-numbers: true
