project:
  type: website
  output-dir: docs

website:
  title: "Pranjal Chatterjee"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog

format:
  html:
    css: assets/theme.css
    highlight-style: github
    code-copy: true
    code-line-numbers: true
